name: Update GitHub Profile ASCII Art

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyfiglet

    - name: Create update_profile.py
      run: |
        cat << EOF > update_profile.py
        import os
        import requests
        from datetime import datetime
        from pyfiglet import Figlet

        def get_github_activity(username):
            url = f"https://api.github.com/users/{username}/events/public"
            headers = {"Authorization": f"token {os.environ['GITHUB_TOKEN']}"}
            response = requests.get(url, headers=headers)
            response.raise_for_status()
            return response.json()

        def create_ascii_art(text):
            f = Figlet(font='slant')
            return f.renderText(text)

        def format_activity(activity):
            event_type = activity['type'].replace('Event', '')
            repo = activity['repo']['name']
            created_at = datetime.strptime(activity['created_at'], "%Y-%m-%dT%H:%M:%SZ")
            return f"{created_at.strftime('%Y-%m-%d %H:%M')} | {event_type:15} | {repo}"

        try:
            username = "zoa-sh"  # Replace with your GitHub username
            activities = get_github_activity(username)

            ascii_header = create_ascii_art("Zoa's GitHub")

            output = f"{ascii_header}\n\n"
            output += "Recent Activity:\n"
            output += "-" * 60 + "\n"

            for activity in activities[:5]:  # Display last 5 activities
                output += format_activity(activity) + "\n"

            output += "-" * 60 + "\n"
            output += f"\nLast updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"

            print("Content to be written to README.md:")
            print(output)

            with open("README.md", "w") as f:
                f.write(f"```\n{output}\n```")

            print("README.md has been updated successfully.")
            
            # Debug: Check file contents after writing
            with open("README.md", "r") as f:
                print("Contents of README.md after writing:")
                print(f.read())

        except Exception as e:
            print(f"An error occurred: {str(e)}")
            raise
        EOF

    - name: Update profile with ASCII art
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python update_profile.py
        echo "Current directory contents:"
        ls -la
        echo "README.md permissions:"
        ls -l README.md

    - name: Check README content
      run: |
        echo "README.md contents:"
        cat README.md
        echo "File size of README.md:"
        wc -c README.md

    - name: Commit and push changes
      run: |
        git config --local user.email "zoa@zoa.sh"
        git config --local user.name "zoa-sh"
        git status
        git add README.md
        git status
        git commit -m "Update profile ASCII art" || echo "No changes to commit"
        git push || echo "No changes to push"
