name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Options
          user: zoa-sh
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_york
          
          # Terminal template
          config_display: large
          
          # Plugins
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_isocalendar: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
